# Generated by Django 4.1.3 on 2022-11-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedrun_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='demos',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='players',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='splits',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='subcategory',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='video',
            field=models.TextField(blank=True),
        ),
    ]
