# Generated by Django 4.1.3 on 2022-11-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedrun_db', '0003_alter_category_options_alter_run_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='date',
            field=models.DateField(),
        ),
    ]
