# Generated by Django 4.1.3 on 2022-12-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedrun_db', '0004_alter_run_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='offset',
            field=models.IntegerField(default=0)
        ),
    ]
